#!/bin/sh
JAVALIB=/segfs/tango/lib/java;
JAVABIN=/segfs/tango/bin/java;
CLASSPATH=$JAVALIB/TangORB.jar:/segfs/dserver/lib/java/Taco.jar:AVABIN/atkpanel.jar:$JAVALIB/HdbTools.jar:$JAVALIB/ATKCore.jar:$JAVALIB/ATKWidget.jar:.
export CLASSPATH
echo $CLASSPATH
echo   Starting...
java -DTANGO_HOST=$TANGO_HOST jive.MainPanel
