#!/bin/sh
JAVALIB=/segfs/tango/release/java/lib;
JAVABIN=/segfs/tango/release/java/appli;
CLASSPATH=$JAVALIB/TangORB.jar:/segfs/dserver/lib/java/Taco.jar:AVABIN/atkpanel.jar:$JAVALIB/HdbTools.jar:$JAVALIB/ATKCore.jar:$JAVALIB/ATKWidget.jar:.
export CLASSPATH
echo $CLASSPATH
echo   Starting...
java -DTANGO_HOST=$TANGO_HOST jive3.MainPanel
